<?php

defined('ABSPATH') || exit;

define("FN_OUTGOING_REVERSED_VAT", 2614);
define("FN_INCOMING_CALCULATED_VAT", 2645);
define("FN_PAYOUT_FEE_VAT", 2641);
define("FN_PAYOUT_DOCTYPE", 'voucher');
define("FN_PAYOUT_FEE_ACCOUNT", 6570);
define("FN_PAYOUT_BANK_ACCOUNT", 1930);
define("FN_ZETTLE_FEE_ACCOUNT", 6570);
